os: linux
language: php
php:
    - 8.0
before_script:
    - composer install
script:
    - mkdir -p build/test
    - apps/MusicLabelApp/backend/bin/console app:dump-env test --env test
    - apps/MusicLabelApp/backend/bin/console doctrine:database:drop --force --quiet
    - apps/MusicLabelApp/backend/bin/console doctrine:database:create --no-interaction --quiet
    - apps/MusicLabelApp/backend/bin/console doctrine:schema:update --force --no-interaction --quiet
    - XDEBUG_MODE=coverage vendor/bin/phpunit -c phpunit.xml.dist
after_success:
    - travis_retry php vendor/bin/php-coveralls
    - travis_retry php vendor/bin/php-coveralls -v