#!/usr/bin/env bash
# ____________________________________________________________________________________________
# How to use this script?
#
# Execute at root:
# ./console [symfony console command]
#
# Example:
# ./console debug:router
# ____________________________________________________________________________________________

docker exec -it docker-symfony-php apps/MusicLabelApp/backend/bin/console $@