#!/usr/bin/env bash
# ____________________________________________________________________________________________
# How to use this script?
#
# Execute at root:
# ./console [symfony console command]
#
# Example:
# ./console debug:router
# ____________________________________________________________________________________________

# FOO="${VARIABLE:-default}"  # If variable not set or null, use default.
# FOO="${VARIABLE:=default}"  # If variable not set or null, set it to default.

ENV="${ENV:-prod}"

if [ ! "$(docker ps | grep docker-symfony-php)" ]; then
  make $ENV-start
fi

docker exec -it docker-symfony-php apps/MusicLabelApp/backend/bin/console $@