#!/usr/bin/env bash
# ____________________________________________________________________________________________
# How to use this script?
#
# Execute at root:
# ./console [symfony console command]
#
# Example:
# ./console debug:router
# ____________________________________________________________________________________________

if [ ! "$(docker ps -a | grep docker-symfony-php)" ]; then
  make dev-start
fi

docker exec -it docker-symfony-php apps/MusicLabelApp/backend/bin/console $@