version: "3.9"

#
# base docker-compose file
#

services:

    php:
        image: masfernandez/${COMPOSE_PROJECT_NAME}-php-${ENV}:${VERSION}
        build:
            context: ./docker/php
            target: ${ENV}
            args:
                PHP_VERSION: ${PHP_VERSION}
        container_name: ${COMPOSE_PROJECT_NAME}-php
        volumes:
            - .:/var/www/html
            - ./docker/php/etc/supervisor/conf.d:/etc/supervisor.d
        networks:
            - musiclabel
            - db
            - redis

networks:
    musiclabel:
    db:
    redis:
    elk: