version: "3.4"

services:

    php:
        container_name: ${COMPOSE_PROJECT_NAME}-php
        image: masfernandez/php8-dev:latest
        volumes:
            - .:/var/www/html
            - ./docker/php/usr/local/etc/php/conf.d/symfony.dev.ini:/usr/local/etc/php/conf.d/symfony.ini
            - ./docker/php/usr/local/etc/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
        networks:
            - php

networks:
    php: