<?php

// This file was generated by running "bin/console dump-env test"

return array (
  'APP_ENV' => 'test',
  'MYSQL_DBNAME' => '',
  'MYSQL_HOST' => '',
  'MYSQL_PORT' => '',
  'SQLITE_DB_URL' => 'sqlite:///%project.root_path%/var/db/sqlite.db',
  'SHELL_VERBOSITY' => 'DEBUG',
  'CORS_ALLOW_ORIGIN' => '^https?://(localhost|127\\.0\\.0\\.1|0\\.0\\.0\\.0)(:[0-9]+)?$',
  'FAILED_TRANSPORT_DSN' => 'doctrine://default?queue_name=failed',
  'ASYNC_TRANSPORT_DSN' => 'in-memory://',
  'SYNC_TRANSPORT_DSN' => 'sync://',
  'LOG_LEVEL_MAIN' => 'DEBUG',
  'LOG_LEVEL_CONSOLE' => 'DEBUG',
  'JWT_ISSUED_BY' => 'https://musiclabel.masfernandez.com',
  'JWT_PERMITTED_FOR' => 'https://api.musiclabel.masfernandez.com',
  'JWT_BE_USED_AFTER' => '+1 second',
  'JWT_EXPIRES_AT' => '+24 hour',
  'APP_SECRET' => 'app-secret-here',
  'SYMFONY_DEPRECATIONS_HELPER' => '1',
  'JWT_CONTENTS' => 'M-tY0FyLshg53XEX',
  'JWT_IDENTIFIED_BY' => '85jgFpu1zqa8jV-d',
  'JWT_PASSPHRASE' => 'Lt-_rX5ge_UlFimu',
  'MYSQL_PASS' => 'not used in test',
  'MYSQL_USER' => 'not used in test',
  'RABBIT_PASS' => 'not used in test',
  'RABBIT_USER' => 'not used in test',
);
