<?php

declare(strict_types=1);

namespace Masfernandez\Tests\MusicLabel\Auth\Domain\Model\Token;

use Masfernandez\MusicLabel\Shared\Domain\User\TokenId;

class TokenIdMother
{
    public static function create(
        ?int $id = PHP_INT_MAX,
    ): TokenId {
        // id null will be auto-generated by DB
        return new TokenId(
            value: $id,
        );
    }
}
