doctrine:
  dbal:
    types:
      AlbumId: Masfernandez\MusicLabel\Catalog\Infrastructure\Persistence\Doctrine\Types\DoctrineAlbumId
      AlbumTitle: Masfernandez\MusicLabel\Catalog\Infrastructure\Persistence\Doctrine\Types\DoctrineAlbumTitle
      AlbumPublishingDate: Masfernandez\MusicLabel\Catalog\Infrastructure\Persistence\Doctrine\Types\DoctrineAlbumPublishingDate