monolog:
    handlers:
        main:
            type: stream
            path: "%app.root_path%/var/log/symfony/MusicLabelApp/%kernel.environment%.log"
            level: debug
            channels: ["!event"]
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine", "!console"]
            path: "%app.root_path%/var/log/symfony/MusicLabelApp/%kernel.environment%.log"
