doctrine:
    dbal:
        dbname: '%env(MYSQL_DBNAME)%'
        host: '%env(MYSQL_HOST)%'
        port: '%env(MYSQL_PORT)%'
        user: '%env(MYSQL_USER)%'
        password: '%env(MYSQL_PASS)%'
        driver: pdo_mysql
        server_version: '8.0'
        charset: utf8mb4
        logging: '%kernel.debug%'

    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            # MusicLabel / Catalog
            Masfernandez\MusicLabel\Catalog\Domain\Model:
                is_bundle: false
                type: xml
                dir: '%project.root_path%/src/MusicLabel/Catalog/Infrastructure/Persistence/Doctrine/db-mappings'
                prefix: 'Masfernandez\MusicLabel\Catalog\Domain\Model'
                alias: Masfernandez\MusicLabel\Catalog\Domain\Model
            # MusicLabel / Auth
            Masfernandez\MusicLabel\Auth\Domain\Model:
                is_bundle: false
                type: xml
                dir: '%project.root_path%/src/MusicLabel/Auth/Infrastructure/Persistence/Doctrine/db-mappings'
                prefix: 'Masfernandez\MusicLabel\Auth\Domain\Model'
                alias: Masfernandez\MusicLabel\Auth\Domain\Model
            # Others bounded contexts here...