nelmio_cors:
    defaults:
        allow_credentials: false
        allow_origin: [ ]
        allow_headers: [ ]
        allow_methods: [ ]
        expose_headers: [ '*' ]
        max_age: 0
        hosts: [ ]
        origin_regex: false
        forced_allow_origin_value: ~
    paths:
#        '^/api/':
#            allow_origin: [ '*' ]
#            allow_headers: [ 'X-Custom-Auth' ]
#            allow_methods: [ 'POST', 'PUT', 'GET', 'DELETE' ]
#            max_age: 3600
        '^/authentication/':
            allow_credentials: true
            allow_origin: [ 'http://localhost:3000', 'http://0.0.0.0:3000', 'http://localhost:5000' ]
            allow_headers: [ '*' ]
            expose_headers: [ 'Location' ]
            allow_methods: [ 'POST', 'PUT', 'GET', 'DELETE', 'OPTIONS' ]
            max_age: 120