<?php

return array (
  'APP_SECRET' => NULL,
  'ASYNC_TRANSPORT_DSN' => NULL,
  'JWT_CONTENTS' => NULL,
  'JWT_IDENTIFIED_BY' => NULL,
  'JWT_PASSPHRASE' => NULL,
  'MYSQL_PASS' => NULL,
  'MYSQL_USER' => NULL,
);
