monolog:
    handlers:
        # deprecation:
        #    See deprecations.yaml file
        events:
            type: stream
            level: '%env(LOG_LEVEL_EVENTS)%'
            path: "%project.root_path%/var/log/symfony/MusicLabelApp/%kernel.environment%.events.log"
            channels: ["event"]
        main:
            type: rotating_file
            level: '%env(LOG_LEVEL_MAIN)%'
            max_files: 30
            path: "%project.root_path%/var/log/symfony/MusicLabelApp/%kernel.environment%.log"
            channels: ["!event"]
        console:
            type: console
            level: '%env(LOG_LEVEL_CONSOLE)%'
            process_psr_3_messages: false
            channels: ["!event", "!doctrine", "!console"]
            path: "%project.root_path%/var/log/symfony/MusicLabelApp/%kernel.environment%.log"