parameters:

    project.root_path: '%kernel.project_dir%/../../..'

    # jwToken config
    jwt.issued_by: '%env(JWT_ISSUED_BY)%'
    jwt.identified_by: '%env(JWT_IDENTIFIED_BY)%' # defined in vault
    jwt.permitted_for: '%env(JWT_PERMITTED_FOR)%'
    jwt.be_used_after: '%env(JWT_BE_USED_AFTER)%'
    jwt.expires_at: '%env(JWT_EXPIRES_AT)%'

services:
    #
    # default configuration for services in *this* file
    #
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false       # Private services by default

        bind:
            $rootPath: '%kernel.project_dir%'
            $defaultBus: '@default.bus'
            $queryBus: '@query.bus'
            $commandBus: '@command.bus'
            $eventBus: '@event.bus'
            Redis $redis: '@snc_redis.default'

    #
    # Symfony
    #
    Masfernandez\MusicLabel\Infrastructure\Api\:
        resource: '%kernel.project_dir%/src/'
        exclude:
            - '%kernel.project_dir%/src/DependencyInjection/'
            - '%kernel.project_dir%/src/Entity/'
            - '%kernel.project_dir%/src/Kernel.php'
            - '%kernel.project_dir%/src/Tests/'

    #
    # Controllers
    #
    Masfernandez\MusicLabel\Infrastructure\Api\Controller\:
        resource: '%kernel.project_dir%/src/Controller/'
        tags: [ 'controller.service_arguments' ]

    #
    # Business logic
    #
    Masfernandez\MusicLabel\:
        resource: '%project.root_path%/src/'

    #
    # JWT
    #
    JwtInMemory:
        class: 'Lcobucci\JWT\Signer\Key\InMemory'
        factory: [ 'Lcobucci\JWT\Signer\Key\InMemory','plainText' ]
        # JWT_CONTENTS, JWT_PASSPHRASE defined in vault -> ./console secrets:list --reveal
        arguments: [ '%env(JWT_CONTENTS)%','%env(JWT_PASSPHRASE)%' ]

    Lcobucci\JWT\Signer\Hmac\Sha256:
        class: Lcobucci\JWT\Signer\Hmac\Sha256

    Configuration:
        class: 'Lcobucci\JWT\Configuration'
        factory: [ 'Lcobucci\JWT\Configuration', 'forSymmetricSigner' ]
        arguments: [ '@Lcobucci\JWT\Signer\Hmac\Sha256','@JwtInMemory' ]

    TokenConfig:
        class: 'Masfernandez\MusicLabel\Infrastructure\Api\Jwt\TokenConfig'
        arguments:
            - '%jwt.issued_by%'
            - '%jwt.identified_by%'
            - '%jwt.permitted_for%'
            - '%jwt.be_used_after%'
            - '%jwt.expires_at%'

    Masfernandez\MusicLabel\Infrastructure\Api\Jwt\Generator:
        public: true
        arguments: [ '@Configuration', '@TokenConfig' ]

    Masfernandez\MusicLabel\Infrastructure\Api\Jwt\Validator:
        public: true
        arguments: [ '@Configuration' , '@TokenConfig']


    #
    # Messenger handlers
    #
    Masfernandez\MusicLabel\Auth\Application\Jwt\Authenticate\JwTokenAuthenticator:
        tags:
            - name: messenger.message_handler
              bus: command.bus
              method: execute
              handles: Masfernandez\MusicLabel\Auth\Application\Jwt\Authenticate\AuthenticateJwTokenCommand

    Masfernandez\MusicLabel\Auth\Application\Jwt\NewToken\NewJwtCreator:
        tags:
            - name: messenger.message_handler
              bus: query.bus
              method: execute
              handles: Masfernandez\MusicLabel\Auth\Application\Jwt\NewToken\GetJwtQuery

    Masfernandez\MusicLabel\Auth\Application\Token\Authenticate\TokenAuthenticator:
        tags:
            - name: messenger.message_handler
              bus: command.bus
              method: execute
              handles: Masfernandez\MusicLabel\Auth\Application\Token\Authenticate\AuthenticateTokenCommand

    Masfernandez\MusicLabel\Auth\Application\Token\GetNewToken\NewTokenCreator:
        tags:
            - name: messenger.message_handler
              bus: query.bus
              method: execute
              handles: Masfernandez\MusicLabel\Auth\Application\Token\GetNewToken\GetTokenQuery

    Masfernandez\MusicLabel\Auth\Application\User\CreateNewUser\UserCreator:
        tags:
            - name: messenger.message_handler
              bus: command.bus
              method: execute
              handles: Masfernandez\MusicLabel\Auth\Application\User\CreateNewUser\NewUserCommand

    Masfernandez\MusicLabel\Catalog\Application\Album\Delete\AlbumDeleter:
        tags:
            - name: messenger.message_handler
              bus: command.bus
              method: execute
              handles: Masfernandez\MusicLabel\Catalog\Application\Album\Delete\DeleteAlbumCommand

    Masfernandez\MusicLabel\Catalog\Application\Album\Get\Collection\AlbumsSearcher:
        tags:
            - name: messenger.message_handler
              bus: query.bus
              method: execute
              handles: Masfernandez\MusicLabel\Catalog\Application\Album\Get\Collection\GetAlbumsQuery

    Masfernandez\MusicLabel\Catalog\Application\Album\Get\Single\AlbumSearcher:
        tags:
            - name: messenger.message_handler
              bus: query.bus
              method: execute
              handles: Masfernandez\MusicLabel\Catalog\Application\Album\Get\Single\GetAlbumQuery

    Masfernandez\MusicLabel\Catalog\Application\Album\Patch\AlbumPatcher:
        tags:
            - name: messenger.message_handler
              bus: command.bus
              method: execute
              handles: Masfernandez\MusicLabel\Catalog\Application\Album\Patch\PatchAlbumCommand

    Masfernandez\MusicLabel\Catalog\Application\Album\Post\AlbumCreator:
        tags:
            - name: messenger.message_handler
              bus: command.bus
              method: execute
              handles: Masfernandez\MusicLabel\Catalog\Application\Album\Post\PostAlbumCommand

    Masfernandez\MusicLabel\Catalog\Application\Album\Put\AlbumUpdater:
      tags:
        - name: messenger.message_handler
          bus: command.bus
          method: execute
          handles: Masfernandez\MusicLabel\Catalog\Application\Album\Put\PutAlbumCommand

    Masfernandez\MusicLabel\Management\Application\Email\Send\EmailOnAlbumCreatedListener:
      tags:
        - name: messenger.message_handler
          bus: event.bus
          method: execute
          handles: Masfernandez\MusicLabel\Catalog\Domain\Album\AlbumCreatedDomainEvent