framework:
  default_locale: '%locale%'

  translator:
    paths:
      - '%kernel.project_dir%/src/Infrastructure/Framework/Symfony/translations'
    fallbacks:
      - '%locale%'
    enabled: false
