filebeat.modules:
- module: nginx
  access:
      enabled: true
      var.paths: ["/tmp/app/logs/nginx/*.access.log"]
  error:
      enabled: true
      var.paths: ["/tmp/app/logs/nginx/*.error.log"]

setup.template.name: "filebeat-"
setup.template.pattern: "filebeat-*"
#setup.dashboards.enabled: true # execute "make filebeat-dashboards" after starting completed because errors

output.elasticsearch:
    hosts: ["http://host.docker.internal:9200"]
    username: root
    password: toor
    index: "filebeat-%{[beat.version]}-%{+yyyy.MM.dd}"

setup.kibana:
    host: http://host.docker.internal:5601