#
# Home
#

web_app_home:
    path: /
    defaults: { _controller: 'App\Infrastructure\UserInterface\Web\Controller\Home\HomeController:action' }
    methods:  [GET]

#
# Albums
#

web_app_album_getall:
    path: /album
    defaults: { _controller: 'App\Infrastructure\UserInterface\Web\Controller\Album\GetAllController:action' }
    methods:  [GET]

web_app_album_add:
    path: /album/new
    defaults: { _controller: 'App\Infrastructure\UserInterface\Web\Controller\Album\AddController:action' }
    methods:  [GET|POST]

web_app_album_update:
    path: /album/edit/{id}
    defaults: { _controller: 'App\Infrastructure\UserInterface\Web\Controller\Album\UpdateController:action' }
    methods:  [GET|POST]

web_app_album_delete:
    path: /album/delete/{id}
    defaults: { _controller: 'App\Infrastructure\UserInterface\Web\Controller\Album\DeleteController:action' }
    methods:  [GET]

#
# Artist
#

web_app_artist_getAll:
    path: /artists
    defaults: { _controller: 'App\Infrastructure\UserInterface\Web\Controller\Artist\GetAllController:action' }
    methods:  [GET|POST]

web_app_artist_add:
    path: /artist
    defaults: { _controller: 'App\Infrastructure\UserInterface\Web\Controller\Artist\AddController:action' }
    methods:  [GET|POST]

web_app_artist_update:
    path: /artist/{id}
    defaults: { _controller: 'App\Infrastructure\UserInterface\Web\Controller\Artist\UpdateController:action' }
    methods:  [GET|POST]

web_app_artist_delete:
    path: /artist/{id}/delete
    defaults: { _controller: 'App\Infrastructure\UserInterface\Web\Controller\Artist\DeleteController:action' }
    methods:  [GET]