parameters:

services:

    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false       # Private services by default


    # Include Tests
    Masfernandez\Tests\:
        resource: '%project.root_path%/tests/'


    # Behatch services
    Behatch\HttpCall\Request:
        arguments:
            - '@behat.mink'

    Behatch\Context\RestContext:
        arguments:
            - '@Behatch\HttpCall\Request'

    Behatch\HttpCall\HttpCallResultPool:
        class: Behatch\HttpCall\HttpCallResultPool

    Behatch\Context\JsonContext:
        arguments:
            - '@Behatch\HttpCall\HttpCallResultPool'


    # Aliases tests
    Masfernandez\Tests\Shared\Domain\Persistence\RepositoryCleaner: '@Masfernandez\Tests\Shared\Infrastructure\Persistence\Sqlite\SqliteCleaner'


    # Aliases common
    Masfernandez\Shared\Domain\Bus\Event\EventPublisher: '@Masfernandez\Shared\Infrastructure\Bus\Event\InMemory\InMemoryEventPublisher'
    Masfernandez\Shared\Application\Service\TransactionalSession: '@Masfernandez\Shared\Infrastructure\Service\NoTransactionalSession'


    # Catalog
    Masfernandez\MusicLabel\Catalog\Domain\Model\Album\AlbumRepository: '@Masfernandez\MusicLabel\Catalog\Infrastructure\Persistence\Doctrine\Repository\DoctrineAlbumRepository'
    Masfernandez\MusicLabel\Catalog\Domain\Model\Album\CacheInMemory: '@Masfernandez\MusicLabel\Catalog\Infrastructure\Persistence\InMemory\Client'
