parameters:

services:

    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false       # Private services by default


    # Redis
    Redis: '@snc_redis.default'
    Masfernandez\MusicLabel\Catalog\Infrastructure\Persistence\Redis\Client:
        public : true
        autowire: true
        arguments: ['@snc_redis.default']


    # Aliases common
    Masfernandez\Shared\Domain\Bus\Event\EventPublisher: '@Masfernandez\Shared\Infrastructure\Bus\Event\RabbitMq\RabbitMqEventPublisher'
    Masfernandez\Shared\Application\Service\TransactionalSession: '@Masfernandez\Shared\Infrastructure\Service\DoctrineTransactionalSession'


    # Catalog
    Masfernandez\MusicLabel\Catalog\Domain\Model\Album\AlbumRepository: '@Masfernandez\MusicLabel\Catalog\Infrastructure\Persistence\Doctrine\Repository\DoctrineAlbumRepository'
    Masfernandez\MusicLabel\Catalog\Domain\Model\Album\CacheInMemory: '@Masfernandez\MusicLabel\Catalog\Infrastructure\Persistence\Redis\Client'
